import Link from "next/link";

/**
 * Simple Wikipedia-style footer with attribution and links.
 */
export function Footer() {
  return (
    <footer className="w-full border-t border-wiki-border bg-wiki-light-bg mt-auto">
      <div className="mx-auto max-w-7xl px-4 py-6">
        {/* Attribution */}
        <p className="text-sm text-[#54595D] text-center mb-3">
          Powered by{" "}
          <span className="font-semibold text-[#202122]">
            Blockify IdeaBlocks
          </span>{" "}
          + LLM Compilation
        </p>

        {/* Links */}
        <div className="flex items-center justify-center gap-4 text-sm mb-3">
          <Link
            href="/about"
            className="text-wiki-link hover:text-wiki-link-hover"
          >
            About
          </Link>
          <span className="text-[#A2A9B1]" aria-hidden="true">
            |
          </span>
          <Link
            href="/pipeline"
            className="text-wiki-link hover:text-wiki-link-hover"
          >
            Pipeline
          </Link>
          <span className="text-[#A2A9B1]" aria-hidden="true">
            |
          </span>
          <a
            href="https://github.com"
            target="_blank"
            rel="noopener noreferrer"
            className="text-wiki-link hover:text-wiki-link-hover"
          >
            GitHub
          </a>
        </div>

        {/* Copyright */}
        <p className="text-xs text-[#72777D] text-center">
          Content compiled from public knowledge sources. All article content is
          generated by LLMs from IdeaBlock data.
        </p>
      </div>
    </footer>
  );
}

export default Footer;
